# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Your awesome title
email: your-email@domain.com
description: Test
baseurl: "/persons"
url: "http://example.org"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
gems:
    - jekyll-rdf
jekyll_rdf:
    path: "rdf-data/persons.ttl"
    language: "en"
    include_blank: true
    render_orphaned_uris: true
    restriction: "SELECT ?resourceUri WHERE { ?resourceUri a <http://xmlns.com/foaf/0.1/Person> }"
    default_template: "rdf_index.html"
    class_template_mappings:
        "http://xmlns.com/foaf/0.1/Person": "person.html"
