
# Site settings
url: http://yoursite.com
title: Your awesome title
email: your-email@domain.com
description: jekyll-rdf businesscards
baseurl: ""

# Build settings
markdown: kramdown
permalink: pretty


# jekyll-rdf
gems:
    - jekyll-rdf
jekyll_rdf:
    path: "rdf-data/persons.ttl"
    language: "en"
    include_blank: true
    render_orphaned_uris: true
    restriction: "SELECT ?resourceUri WHERE { { ?resourceUri a <http://xmlns.com/foaf/0.1/Person> . } UNION { ?resourceUri a <http://example.org/group> . } }"
    default_template: "default.html"
    class_template_mappings:
        "http://xmlns.com/foaf/0.1/Person" : "person.html"
        "http://example.org/group" : "group.html"
